# This is a basic workflow to help you get started with Actions

name: ESLint Action

on:
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: hallee/eslint-action@1.0.1
