name: AJ Continous integration

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - uses: actions/checkout@v1
      - name: Run Jest
      uses: stefanoeb/jest-action@1.0.2